### ISSUE TITLE
A problem about the "unknown device"

### ISSUE THREAD

**Issue by wyatuestc** [emsec/ChameleonMini#10]
I made a ChameleonMini by myself.
Here is my step to download the firmware:
1. connect the board to PC
2. use avr isp mkii to download the bootloader(RevE-atxmega32a4u_104_modified.hex)
![image](https://cloud.githubusercontent.com/assets/3883941/9328872/2f413ff8-45df-11e5-9afc-dc3ac84ef899.png)

I can see a device named ATxmega32A4U
![image](https://cloud.githubusercontent.com/assets/3883941/9328867/1efbada4-45df-11e5-8d7a-53f4ec569c5b.png)

3.after that, I dowload the firmware/eeprom Chameleon-Mini.hex/Chameleon-Mini.elf with avr isp mkii,and I got this:"Unknown device"(at that time, one led turns on), and I also use the FLIP to download the firmware/eeprom, I got the same result.

![image](https://cloud.githubusercontent.com/assets/3883941/9328911/9427f894-45df-11e5-8cc5-11ff17fb856b.png)

![image](https://cloud.githubusercontent.com/assets/3883941/9328917/a4e1d20e-45df-11e5-922f-42d6d9de629e.png)

I want to know what happened.

Tanks :)

--------------------------------------------
I can download the frimware which is provided by the AVR studio6
![image](https://cloud.githubusercontent.com/assets/3883941/9329131/97961edc-45e1-11e5-88ec-376121b87952.png)

and I got this 
![image](https://cloud.githubusercontent.com/assets/3883941/9329123/7eb5bf9e-45e1-11e5-9f2c-2c8002c1c4da.png)

It seemed like working well...

**Comment by wyatuestc** [comment]
There must be something wrong.
When I open VMware and run a virtual machine(ubuntu 14.04),  I found the hardware is working, I test it many times.....
It's wired....
I guess there is something wrong in the USB driver......


![image](https://cloud.githubusercontent.com/assets/3883941/9336218/053c1fb2-460b-11e5-98dd-65f4ca70675f.png)

![image](https://cloud.githubusercontent.com/assets/3883941/9336226/0b212da0-460b-11e5-99fc-1a877c1d49ff.png)

**Comment by wyatuestc** [comment]
I think I solve problem when I used the newest firmware....
There are something promblems on my hardware.....

**Comment by david-oswald** [comment]
Yes, you for sure need the newest FW - the older one contained a bug that caused the Chameleon to fail with newer Flash chips (actually this error should have also affected older Flash, but it seemed more tolerant). Anyway, this is fixed in the new FW.

Re VMWare: Have not tried, any reason why you need this? Also, wasn't VMware working before (and now stopped)? Strange bug, if you find out anything pls let us know.

Re command line: Have you seen this page: https://htmlpreview.github.io/?https://raw.githubusercontent.com/emsec/ChameleonMini/master/Doc/Doxygen/html/_page__command_line.html

**Comment by theforcedk** [comment]
In order to use USB's in virtualized environments, you usually have to add filters to ensure that the USB is grabbed by the guest OS before the host OS when plugged in, otherwise you'll get stability issues and the USB will connect/disconnect/connect/disconnect. For VirtualBox, this works with ChameleonMini: http://www.atmel.com/webdoc/atmelstudio/atmelstudio.faq.virtualbox.html
