### ISSUE TITLE
New GUI reloaded for RevG available

### ISSUE THREAD

**Issue by gtpy** [emsec/ChameleonMini#168]
Another GUI for ChameleonMini RevG is growing up...

Here the first screens:
![mainform](https://user-images.githubusercontent.com/13873777/36449369-f15d1fb6-168a-11e8-9392-e12efb39c222.png)
![identify](https://user-images.githubusercontent.com/13873777/36449376-f3b27c7a-168a-11e8-8a13-9c43ec72b13c.png)
![settings](https://user-images.githubusercontent.com/13873777/36449379-f52ded46-168a-11e8-9440-3ea3d0e4af35.png)
![logging](https://user-images.githubusercontent.com/13873777/36449383-f715d844-168a-11e8-8c1c-4806e30a2b1f.png)

Other features will follow soon

first impressions?

**Comment by gtpy** [comment]
Repo is now available:
https://github.com/gtpy/ChameleonMini-RevG-GUI

**Comment by iceman1001** [comment]
Nice one!   I like the idea with a picture of the device...   I'm gonna use that idea :)

**Comment by maxieds** [comment]
Is this GUI going to be available on Linux at some point? It would make sense to use a portable GUI layer to implement the core functionality of the GUI and let the user choose where it gets compiled. I have tried to use Windows sanely, I really did, but made it 3 weeks before wiping the drive and giving myself a usable command line back. This would be **really** nice if it worked on my Debian-variant Linux box. :) Otherwise, for Linux only users, there's [my app](https://github.com/maxieds/ChameleonMiniLiveDebugger) on Android platforms.

**Comment by iceman1001** [comment]
@maxieds   there is a GUI implemented in GO,    https://github.com/emsec/ChameleonMini/issues/167#issuecomment-367091177    that should work on linux.

**Comment by geo-rg** [comment]
Thanks, @gtpy! I added a link in the wiki!
