### ISSUE TITLE
Chameleon mini Rev G (MF Detection/Reader attack)

### ISSUE THREAD

**Issue by nico0481** [emsec/ChameleonMini#226]
Hello,

Is the Chameleon mini Rev G able to do reader attack (MF Detection).
With which firmware?
I can't find a way to do this.

Thank you

Best regards

Nico

**Comment by gtpy** [comment]
Not with standard firmware.
I had experimented with it a bit, hadn't tested it yet and hadn't finished it.
Need to check my local repos ;)

**Comment by lavanoid** [comment]
I've attempted to bodge this feature into the current Rev G firmware and I'm clueless. I've asked the devs for the RevE Rebooted if they could assist with adding this feature to my fork of the Rev G firmware but they just tell me to go here. Would've been nice if they tried to help :/

https://github.com/lavanoid/ChameleonMini/commit/0ad00933b5aeca77cb0722e145d630c656dbe768

**Comment by gtpy** [comment]
hi @lavanoid I tried the same time ago. found my local repo and pushed it now c8249d5 .

There I don't get problems with red LED. But I am not sure if its working.

Have no experience with detection function and are not sure what exactly is needed.
Maybe it is working, but I need some more tests or hints how to test.
Any Ideas?

I checked your code. Looks almost identical what I have done.

1. Set MF Classic & UID
2. Set Detection
3. Hold on reader
4. Use GUI and mfkey

**Comment by lavanoid** [comment]
I just built the firmware with your commits and it seems to be working, however I have no idea what GUI to use to run mfkey. The latest build of ChameleonMini-rebootedGUI hides the mfkey option when detecting the Rev G.

I thought maybe something would be stored in the Chameleon device logs but I don't seem to have anything in there. 

This is the video I watched, to get an idea of how the MF_DETECT function works: https://www.youtube.com/watch?v=1VpXC3-eKhc

**Comment by gtpy** [comment]
Try my GUI fort Rev G

https://gitlab.com/Gtpy/ChameleonMini-RevG_GUI
It Support the mfkey.

Gesendet von ProtonMail mobile

-------- Original-Nachricht --------
An 25. Aug. 2019, 19:04, Lava Git schrieb:

**Comment by lavanoid** [comment]
That seems to work! Requires a few retries and doesn't always find the keys (might just be because I'm using Mifare Classic Tool on Android and not an actual reader) but it does indeed work.

![image](https://user-images.githubusercontent.com/4705167/63653763-f73ce480-c768-11e9-9ff9-71c93fc3bae9.png)
![image](https://user-images.githubusercontent.com/4705167/63653767-01f77980-c769-11e9-8604-039d7cf4228d.png)
One bug with the GUI is that it doesn't let me change the UID of the tag, so I have to use another tool to do that.

**Comment by gtpy** [comment]
UID changes worked. 
Enter UID --> Change UID.
If it doesn't work, give a short info, then I fix it.

How you check it with MCT? I never tried this :)

**Comment by lavanoid** [comment]
```(doesn't work in detection mode - need to set for example mf_classic_1k)
If it doesn't work, give a short info, then I fix it.``` I'll give it a try when I'm booted into Windows again (only use Windows for games, so not signed into anything personal).

```How you check it with MCT? I never tried this :)```
I have a few key files from previous tags I have dumped. In MCT, I do this:

1.) Select "Read Tag"
2.) Select the key file I have, from a previous tag
3.) Select "Start mapping and read tag"

MCT will then attempt to authenticate with the Chameleon with the keys I told it to use, just like what a reader would do :)

**Comment by gtpy** [comment]
Ok thanks. Need to use MCT more :)
Me too - only Linux user - Win only for games and some GUI stuff

**Comment by lavanoid** [comment]
Greetings, my fellow Linux user 🐱

- Windows for games & password cracking with hashcat (pain controlling GPU overclocks and fan speeds on any Linux distro)
- Manjaro Linux for everything else except Netflix (cuz DRM)
- macOS for Netflix (faster than Windows, 1080p Netflix support on special titles, unix)

**Comment by lavanoid** [comment]
Check out my repo for MF Detection support on the Rev G. It has had some changes made to it, for readers that check the card capacity.

Here is a pre-compiled version with the latest commits in my repo: https://github.com/lavanoid/ChameleonMini/releases/tag/BETA-RevG

**Comment by ceres-c** [comment]
I think it might be time to close this issue @geo-rg @david-oswald

**Comment by Walter-Bishop** [comment]
I tried to use gtpy's code in #229 but it seems their GUI is not available any more 😢: https://gitlab.com/Gtpy/ChameleonMini-RevG_GUI 

@nico0481 do you (or anyone else) still have a copy of it and could upload it here?

I changed the iceman firmware so that it allows to use the mfkey32 attack but it just returns a CRC checksum error. I assume there is some difference in how the data is being transmitted in the Rev. E rebooted firmware and in #229 but I couldn't find any specific difference yet.
