### ISSUE TITLE
My chameleonmini REV_G can't emulate the MF_CLASSIC_1K

### ISSUE THREAD

**Issue by feifeilanniao** [emsec/ChameleonMini#79]
When i try to read my chameleonmini with my Mobile Phone,some problem occur.It seem that the chameleonmini can't communicate with the Phone stably.But when i CONFIG the chameleonmini as MF_ULTRALIGHT,it  perform well.
![s61114-11011503](https://cloud.githubusercontent.com/assets/16999626/20252366/78b53c74-aa5c-11e6-96df-acc2ddd65018.jpg)
![s61114-11022764](https://cloud.githubusercontent.com/assets/16999626/20252367/7d197280-aa5c-11e6-8656-37ecbbb4fa73.jpg)

**Comment by feifeilanniao** [comment]
![s61114-11302348](https://cloud.githubusercontent.com/assets/16999626/20252509/e9b4de7e-aa5d-11e6-928f-a7252d7ff61a.jpg)
emulate the MF_ULTRALIGHT

**Comment by peter-neu** [comment]
Had the same problem, what was the solution to this?

**Comment by feifeilanniao** [comment]
Try to use the battery to supply power.

**Comment by emsec** [comment]
sure that you use the correct secret keys? even when NFC phones have a bad read range (and most of them have a VERY bad read range :) ) there must be some position in which it works. I assume you're using the latest firmware. Otherwise, we need to find out what these Smartphones do different when reading out cards, compared to "normal" readers...  have no idea, yet. But thanks to everyone comtributing to this topic.
