### ISSUE TITLE
Chameleon-mini Xtal - possible to run on internal?

### ISSUE THREAD

**Issue by themartinm** [emsec/ChameleonMini#8]
I got a board fabbed built out a chameleon mini and am wondering about the crystal configuration as I didn't source a xtal. Is it possible to run the chameleon on the internal oscillator only?

From my understanding the local oscillator can supply a sufficient 12mhz clock for the usb.. however, I configured the board to run on the internal but the v-usb never initializes properly.. Any ideas or pointers in the right direction? 

Also the cap values (22pf) seem a little high if using the 12mhz xtal, (http://www.atmel.com/images/doc8072.pdf recommends ~10pf).  I haven't played with the xmega's, I used to be more of a PIC guy so this might be totally irrelevant..
Thanks in advance!

**Comment by skuep** [comment]
Unfortunately it is not possible to use the internal oscillator only, because for RFID we need a 13.56MHz synchronous clock and for USB, we need as you already mentioned a 12 MHz clock.

The "correct" value of the caps actually depends on a lot of factors, not only stray inductance from the ATxmega but also on the required load capacitance by the crystal. Therefore the values in the Atmel document are only meant as a guideline, not a rule.

See ya
